config/routes.rb
Rails.application.routes.draw do

  resources :talents, only: :new
  resources :recruiters, only: :new
  resources :decsions, only: :index
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  belongs_to :user
end

app/models/talent.rb
class Talent < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :talent
  has_one :recruiter
  
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/decsions_controller.rb
class DecsionsController < ApplicationController
  def index
  end
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  def new
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to decsions_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/decsions_helper.rb
module DecsionsHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/decsions/index.html.erb
<h1>Please Select Recruiter or Talent</h1>

<%= link_to "Recruiter", new_recruiter_path %> | <%= link_to "Talent", new_talent_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1Diversityx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if signed_in? %>
      <%= link_to "Sign Out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Sign In", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recruiters/new.html.erb
<h1>Recruiters#new</h1>
<p>Find me in app/views/recruiters/new.html.erb</p>

app/views/talents/new.html.erb
<h1>Talents#new</h1>
<p>Find me in app/views/talents/new.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username, require: true %>
  </div>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name, require: true %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name, require: true %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, require: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, require: true %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>